# Kubernetes Deployment configuration for Estate Kit Frontend Service
# Version: apps/v1
# Purpose: Manages React web application pods with high availability, resource management, and security settings

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: estate-kit
  labels:
    app: estate-kit
    component: frontend
    managed-by: terraform
  annotations:
    description: "Estate Kit frontend web application deployment"
    owner: "DevOps"
    security.estatekit.ca/secure-config: "true"
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"

spec:
  # High availability configuration with 3 replicas
  replicas: 3
  
  # Rolling update strategy for zero-downtime deployments
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  
  # Pod selector configuration
  selector:
    matchLabels:
      app: estate-kit
      component: frontend
  
  template:
    metadata:
      labels:
        app: estate-kit
        component: frontend
    
    spec:
      # Container specifications
      containers:
      - name: frontend
        image: ${ECR_REGISTRY}/estate-kit-frontend:${IMAGE_TAG}
        
        # Container port configuration
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        
        # Resource allocation as per technical specifications
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        
        # Environment configuration from ConfigMaps and Secrets
        envFrom:
        - configMapRef:
            name: app-config
        - configMapRef:
            name: feature-flags
        - secretRef:
            name: auth0-credentials
        
        # Health check configuration
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        
        # Enhanced security context for container
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        
        # Volume mounts for temporary storage
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      
      # Pod-level volumes
      volumes:
      - name: tmp
        emptyDir: {}
      
      # Pod-level security context
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
      
      # Pod anti-affinity for high availability
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: estate-kit
                  component: frontend
              topologyKey: kubernetes.io/hostname