# Kubernetes Namespace Configuration for Estate Kit Application
# Version: v1
# Purpose: Define isolated environment with comprehensive security and resource controls
# Compliance: PIPEDA and HIPAA standards

apiVersion: v1
kind: Namespace
metadata:
  name: estate-kit
  labels:
    app: estate-kit
    environment: ${ENV}
    managed-by: terraform
    security-level: high
    compliance: pipeda-hipaa
  annotations:
    description: "Estate Kit application namespace with enhanced security controls"
    owner: "DevOps"
    compliance: "PIPEDA,HIPAA"
    backup-policy: "daily"
    security.network.k8s.io/monitored: "true"
    security.compliance/last-audit: "${AUDIT_TIMESTAMP}"

---
# Resource Quota configuration for compute, storage, and object limits
apiVersion: v1
kind: ResourceQuota
metadata:
  name: estate-kit-quota
  namespace: estate-kit
spec:
  hard:
    # Compute Resources
    requests.cpu: "16"
    requests.memory: "32Gi"
    limits.cpu: "32"
    limits.memory: "64Gi"
    # Storage Resources
    requests.storage: "500Gi"
    persistentvolumeclaims: "20"
    # Object Count Limits
    pods: "50"
    services: "20"
    configmaps: "30"
    secrets: "30"
    resourcequotas: "5"
    networkpolicies: "10"

---
# LimitRange configuration for container resource constraints
apiVersion: v1
kind: LimitRange
metadata:
  name: estate-kit-limits
  namespace: estate-kit
spec:
  limits:
  - type: Container
    default:
      cpu: "500m"
      memory: "512Mi"
    defaultRequest:
      cpu: "100m"
      memory: "128Mi"
    max:
      cpu: "4"
      memory: "8Gi"
    min:
      cpu: "50m"
      memory: "64Mi"

---
# Default Network Policy - Deny all ingress traffic
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: estate-kit
spec:
  podSelector: {}
  policyTypes:
  - Ingress

---
# Network Policy - Allow traffic from permitted namespaces
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-permitted-namespaces
  namespace: estate-kit
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
          - monitoring
          - ingress-nginx
          - cert-manager
          - logging

---
# Network Policy - Allow DNS and metrics egress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-metrics-egress
  namespace: estate-kit
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - port: 9090
      protocol: TCP