# Kubernetes Secrets configuration for Estate Kit application
# Version: v1
# Enhanced security with AES-256 encryption and automated rotation

apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: estate-kit
  labels:
    app: estate-kit
    component: secrets
    environment: ${ENV}
    managed-by: terraform
    security-tier: high
    rotation-schedule: 30d
    backup-enabled: "true"
  annotations:
    description: "PostgreSQL database credentials"
    owner: "DevOps"
    security-level: "high"
    encryption: "aes256"
    last-rotated: "${TIMESTAMP}"
    rotation-schedule: "0 0 1 * *"
    backup-retention: "90d"
    audit-logging: "enabled"
type: Opaque
data:
  POSTGRES_USER: ${BASE64_POSTGRES_USER}
  POSTGRES_PASSWORD: ${BASE64_POSTGRES_PASSWORD}
  POSTGRES_DB: ${BASE64_POSTGRES_DB}
  POSTGRES_HOST: ${BASE64_POSTGRES_HOST}
  POSTGRES_PORT: ${BASE64_POSTGRES_PORT}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: estate-kit
  labels:
    app: estate-kit
    component: secrets
    environment: ${ENV}
    managed-by: terraform
    security-tier: high
    rotation-schedule: 30d
    backup-enabled: "true"
  annotations:
    description: "Redis cache credentials"
    owner: "DevOps"
    security-level: "high"
    encryption: "aes256"
    last-rotated: "${TIMESTAMP}"
    rotation-schedule: "0 0 1 * *"
    backup-retention: "90d"
    audit-logging: "enabled"
type: Opaque
data:
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}
  REDIS_HOST: ${BASE64_REDIS_HOST}
  REDIS_PORT: ${BASE64_REDIS_PORT}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: estate-kit
  labels:
    app: estate-kit
    component: secrets
    environment: ${ENV}
    managed-by: terraform
    security-tier: high
    rotation-schedule: 30d
    backup-enabled: "true"
  annotations:
    description: "AWS service credentials"
    owner: "DevOps"
    security-level: "high"
    encryption: "aes256"
    last-rotated: "${TIMESTAMP}"
    rotation-schedule: "0 0 1 * *"
    backup-retention: "90d"
    audit-logging: "enabled"
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ${BASE64_AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${BASE64_AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ${BASE64_AWS_REGION}
  AWS_S3_BUCKET: ${BASE64_AWS_S3_BUCKET}
  AWS_KMS_KEY_ID: ${BASE64_AWS_KMS_KEY_ID}
---
apiVersion: v1
kind: Secret
metadata:
  name: auth0-credentials
  namespace: estate-kit
  labels:
    app: estate-kit
    component: secrets
    environment: ${ENV}
    managed-by: terraform
    security-tier: high
    rotation-schedule: 30d
    backup-enabled: "true"
  annotations:
    description: "Auth0 authentication credentials"
    owner: "DevOps"
    security-level: "high"
    encryption: "aes256"
    last-rotated: "${TIMESTAMP}"
    rotation-schedule: "0 0 1 * *"
    backup-retention: "90d"
    audit-logging: "enabled"
type: Opaque
data:
  AUTH0_DOMAIN: ${BASE64_AUTH0_DOMAIN}
  AUTH0_CLIENT_ID: ${BASE64_AUTH0_CLIENT_ID}
  AUTH0_CLIENT_SECRET: ${BASE64_AUTH0_CLIENT_SECRET}
  AUTH0_AUDIENCE: ${BASE64_AUTH0_AUDIENCE}
  AUTH0_CALLBACK_URL: ${BASE64_AUTH0_CALLBACK_URL}
---
apiVersion: v1
kind: Secret
metadata:
  name: sendgrid-credentials
  namespace: estate-kit
  labels:
    app: estate-kit
    component: secrets
    environment: ${ENV}
    managed-by: terraform
    security-tier: high
    rotation-schedule: 30d
    backup-enabled: "true"
  annotations:
    description: "SendGrid email service credentials"
    owner: "DevOps"
    security-level: "high"
    encryption: "aes256"
    last-rotated: "${TIMESTAMP}"
    rotation-schedule: "0 0 1 * *"
    backup-retention: "90d"
    audit-logging: "enabled"
type: Opaque
data:
  SENDGRID_API_KEY: ${BASE64_SENDGRID_API_KEY}
  SENDGRID_FROM_EMAIL: ${BASE64_SENDGRID_FROM_EMAIL}
  SENDGRID_TEMPLATE_ID: ${BASE64_SENDGRID_TEMPLATE_ID}
---
apiVersion: v1
kind: Secret
metadata:
  name: encryption-keys
  namespace: estate-kit
  labels:
    app: estate-kit
    component: secrets
    environment: ${ENV}
    managed-by: terraform
    security-tier: high
    rotation-schedule: 30d
    backup-enabled: "true"
  annotations:
    description: "Application encryption and signing keys"
    owner: "DevOps"
    security-level: "high"
    encryption: "aes256"
    last-rotated: "${TIMESTAMP}"
    rotation-schedule: "0 0 1 * *"
    backup-retention: "90d"
    audit-logging: "enabled"
type: Opaque
data:
  AES_KEY: ${BASE64_AES_KEY}
  JWT_SIGNING_KEY: ${BASE64_JWT_SIGNING_KEY}
  JWT_PUBLIC_KEY: ${BASE64_JWT_PUBLIC_KEY}
  KEY_ROTATION_TIMESTAMP: ${BASE64_KEY_ROTATION_TIMESTAMP}
---
apiVersion: v1
kind: Secret
metadata:
  name: shopify-credentials
  namespace: estate-kit
  labels:
    app: estate-kit
    component: secrets
    environment: ${ENV}
    managed-by: terraform
    security-tier: high
    rotation-schedule: 30d
    backup-enabled: "true"
  annotations:
    description: "Shopify e-commerce integration credentials"
    owner: "DevOps"
    security-level: "high"
    encryption: "aes256"
    last-rotated: "${TIMESTAMP}"
    rotation-schedule: "0 0 1 * *"
    backup-retention: "90d"
    audit-logging: "enabled"
type: Opaque
data:
  SHOPIFY_API_KEY: ${BASE64_SHOPIFY_API_KEY}
  SHOPIFY_API_SECRET: ${BASE64_SHOPIFY_API_SECRET}
  SHOPIFY_STORE_URL: ${BASE64_SHOPIFY_STORE_URL}
  SHOPIFY_WEBHOOK_SECRET: ${BASE64_SHOPIFY_WEBHOOK_SECRET}
---
apiVersion: v1
kind: Secret
metadata:
  name: intercom-credentials
  namespace: estate-kit
  labels:
    app: estate-kit
    component: secrets
    environment: ${ENV}
    managed-by: terraform
    security-tier: high
    rotation-schedule: 30d
    backup-enabled: "true"
  annotations:
    description: "Intercom customer support integration credentials"
    owner: "DevOps"
    security-level: "high"
    encryption: "aes256"
    last-rotated: "${TIMESTAMP}"
    rotation-schedule: "0 0 1 * *"
    backup-retention: "90d"
    audit-logging: "enabled"
type: Opaque
data:
  INTERCOM_ACCESS_TOKEN: ${BASE64_INTERCOM_ACCESS_TOKEN}
  INTERCOM_APP_ID: ${BASE64_INTERCOM_APP_ID}
  INTERCOM_SIGNING_SECRET: ${BASE64_INTERCOM_SIGNING_SECRET}