# Estate Kit Kustomization Configuration
# Version: v1
# Purpose: Manages Kubernetes resources with enhanced security and compliance controls
# Dependencies: kustomize v5.0.0

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources to be included in all environments
resources:
  # Core infrastructure
  - base/namespace.yaml
  - base/configmap.yaml
  - base/secrets.yaml
  
  # Security configurations
  - security/rbac.yaml
  - security/networkpolicies.yaml
  - security/podsecuritypolicies.yaml
  
  # Application components
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  
  # Monitoring stack
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml
  - monitoring/alertmanager.yaml

# ConfigMap generators with environment-specific configurations
configMapGenerator:
  # Application configuration
  - name: app-config
    behavior: merge
    envs:
      - config/app.env
    options:
      disableNameSuffixHash: true
      labels:
        config-type: application
        environment: ${ENV}
        security-tier: high
        compliance: hipaa-pipeda
  
  # Security configuration
  - name: security-config
    behavior: merge
    envs:
      - config/security.env
    options:
      labels:
        config-type: security
        environment: ${ENV}
        security-tier: high
        compliance: hipaa-pipeda

# Secret generators with enhanced security controls
secretGenerator:
  - name: app-secrets
    behavior: merge
    envs:
      - secrets/app.env
    options:
      # Automated secret rotation configuration
      rotation:
        enabled: true
        schedule: "0 0 * * 0"  # Weekly rotation
        backupCount: 3
      # AWS KMS encryption configuration
      encryption:
        provider: aws-kms
        keyId: ${KMS_KEY_ID}
      labels:
        secret-type: application
        environment: ${ENV}
        security-tier: high
        compliance: hipaa-pipeda

# Environment-specific patches
patches:
  # Frontend deployment patches
  - target:
      kind: Deployment
      name: frontend
    path: overlays/frontend-patch.yaml
  
  # Backend deployment patches
  - target:
      kind: Deployment
      name: backend
    path: overlays/backend-patch.yaml
  
  # Security policy patches
  - target:
      kind: NetworkPolicy
      name: default
    path: overlays/security/network-policy-patch.yaml

# Common labels applied to all resources
commonLabels:
  app: estate-kit
  environment: ${ENV}
  managed-by: kustomize
  security-tier: high
  compliance: hipaa-pipeda
  version: ${VERSION}
  backup-enabled: "true"

# Common annotations for documentation and tracking
commonAnnotations:
  maintainer: "DevOps"
  contact: "devops@estatekit.ca"
  description: "Estate Kit application resources"
  security.estatekit.ca/last-audit: ${LAST_SECURITY_AUDIT}
  monitoring.estatekit.ca/alerts: "enabled"
  encryption.estatekit.ca/enabled: "true"
  backup.estatekit.ca/enabled: "true"
  compliance.estatekit.ca/status: "compliant"
  compliance.estatekit.ca/standards: "PIPEDA,HIPAA"

# Namespace configuration
namespace: estate-kit

# Configuration for handling name prefixes and suffixes
namePrefix: "ek-"
nameSuffix: "-${ENV}"

# Resource transformers for consistent configuration
transformers:
  - labels.yaml
  - annotations.yaml
  - securitycontext.yaml

# Configuration for replicas
replicas:
  - name: frontend
    count: 3
  - name: backend
    count: 3
  - name: worker
    count: 2

# OpenAPI validation configuration
openapi:
  path: swagger/openapi.yaml

# Images configuration with explicit versioning
images:
  - name: estate-kit/frontend
    newName: ${ECR_REGISTRY}/estate-kit-frontend
    newTag: ${VERSION}
  - name: estate-kit/backend
    newName: ${ECR_REGISTRY}/estate-kit-backend
    newTag: ${VERSION}
  - name: estate-kit/worker
    newName: ${ECR_REGISTRY}/estate-kit-worker
    newTag: ${VERSION}

# Vars for substitution
vars:
  - name: ENVIRONMENT
    objref:
      kind: ConfigMap
      name: app-config
      apiVersion: v1
    fieldref:
      fieldpath: data.NODE_ENV